2024-01-06 14:55:27,759 {start_app.py:26} - INFO - Execution environment is LOCAL_ENVIRONMENT
2024-01-06 14:55:27,777 {start_app.py:43} - INFO - Initializing app...
2024-01-06 14:55:27,807 {/mnt/c/Users/Maharaj/Downloads/drive-download-20240103T073046Z-001/gstreamer_person_detection_24_oct_2023/gstreamer_person_detection (copy)/src/exception/base_exception.py:21} - ERROR - Exception Occured in Metadatae Service Inition: Error 111 connecting to localhost:6379. Connection refused..
2024-01-06 17:56:49,303 {start_app.py:26} - INFO - Execution environment is LOCAL_ENVIRONMENT
2024-01-06 17:56:49,306 {start_app.py:43} - INFO - Initializing app...
2024-01-06 17:57:53,143 {start_app.py:26} - INFO - Execution environment is LOCAL_ENVIRONMENT
2024-01-06 17:57:53,146 {start_app.py:43} - INFO - Initializing app...
2024-01-06 18:06:16,137 {start_app.py:26} - INFO - Execution environment is LOCAL_ENVIRONMENT
2024-01-06 18:06:16,140 {start_app.py:43} - INFO - Initializing app...
